### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by 223050025** [cuhk-haosun/docker-fastqc#1]
I already created **Dockerfile** and **entrypoint.sh**, but there are some problem.
1. In the NGs, I don't have permission to build docker, the error message is "ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied".
2. So I use my own computer to test, like test minimap2 before. But macOS don't support singularity. So I can't test the docker.

@Milokita

**Comment by Milokita** [comment]
I will create a user for you in the hk.
Plz email me your password

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Li Yixiao ***@***.***>
Sent: Wednesday, August 21, 2024 1:37:57 AM
To: cuhk-haosun/docker-fastqc ***@***.***>
Cc: ZHAO, Xing ***@***.***>; Mention ***@***.***>
Subject: [cuhk-haosun/docker-fastqc] Problem (Issue #1)


I already created Dockerfile and entrypoint.sh, but there are some problem.

  1.  In the NGs, I don't have permission to build docker, the error message is "ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied".
  2.  So I use my own computer to test, like test minimap2 before. But macOS don't support singularity. So I can't test the docker.

@Milokita<https://github.com/Milokita>

**Comment by 223050025** [comment]
The password of Singularity is Lyx001107
发自我的 iPhone

在 2024年8月21日，07:54，zx ***@***.***> 写道：

﻿

I will create a user for you in the hk.
Plz email me your password

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Li Yixiao ***@***.***>
Sent: Wednesday, August 21, 2024 1:37:57 AM
To: cuhk-haosun/docker-fastqc ***@***.***>
Cc: ZHAO, Xing ***@***.***>; Mention ***@***.***>
Subject: [cuhk-haosun/docker-fastqc] Problem (Issue #1)


I already created Dockerfile and entrypoint.sh, but there are some problem.

1. In the NGs, I don't have permission to build docker, the error message is "ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied".
2. So I use my own computer to test, like test minimap2 before. But macOS don't support singularity. So I can't test the docker.

@Milokita<https://github.com/Milokita>
